#!/usr/bin/env bash
# Install nginx if it's not already installed
if ! command -v nginx >/dev/null 2>&1; then
    apt-get update
    apt-get install -y nginx
fi
# Create a configuration file for the redirection
tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
        listen 80;
        server_name _;

        location = /redirect_me {
                return 301 https://www.youtube.com/watch?v=xvFZjo5PgG0;
        }
}
EOF
#        location = /mystery {
#                return 301 https://www.youtube.com/watch?v=xvFZjo5PgG0;
#        }
#}
#EOF
# Make a sympolic link for the default server
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart nginx to apply the changes
service nginx restart
