#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

if ! command -v nginx >/dev/null 2>&1; then
        apt-get update
        apt-get install -y nginx
fi
#Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
#Create a custom index.html
echo "Hello World!" > /var/www/html/custom_404.html
#Create a configuration file for the custom 404 page
tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;
        root /var/www/html;
        index index.html;

	add_header X-Served-By \$hostname;

        location = /redirect_me {
                return 301 https://www.youtube.com/watch?v=xvFZjo5PgG0;
        }

        location = /mystery {
                return 301 https://www.youtube.com/watch?v=xvFZjo5PgG0;
        }

        error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /var/www/html;
                internal;
        }
}
EOF
# Make a sympolic link for the default server
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#Restart nginx to apply changes
service nginx restart
