#!/usr/bin/env bash
#nstall and configure HAproxy on your server.

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 52.90.22.134:80 check
    server web-02 54.158.211.214:80 check
EOF

# Enable HAProxy as a service
sudo systemctl enable haproxy

# Restart HAProxy
sudo service haproxy reload
