#!/usr/bin/env bash
# reload Gunicorn in a graceful way.

#gunicorn_pid=$(pgrep gunicorn)

#shellcheck disable=SC2086
#kill -s HUP $gunicorn_pid

#shellcheck disable=SC2009
ps aux | grep gunicorn | awk '{ print $2 }' | xargs kill -s HUP
